apiVersion: v1
kind: Service

metadata:
  name: web-active
  labels:
    app: web

spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
